CVTrackpad: OpenCV::Bitmap::Image Class Reference
OpenCV::Bitmap::Image Class Reference
Image Implements General Constructors an utilities for manipulate images or CvArray-based Matrix.
#include <Image.h>
Public Member Functions
Image ()
Image (const Image &)
Image (IplImage *)
Image (const char *) throw (FileNotFoundException)
Image (CvSize, int=UByte, int=3)
Default Constructor.
virtual ~Image ()
CvSize size () const
Gets Image's Size.
int width () const
int height () const
int depth () const
Gets Color Depth from enum Depth.
int numberOfChannels () const
Gets channels Count. 3 for color or 1 for BW.
char * rawData ()
Gets pointer for image's RAW data(Bitmap). Be careful with big-endian processors.
IplImage * cvImage () const
Gets pointer to OpenCV's image format.
void setCvImage (IplImage *cvImage)
Sets OpenCV's Image. It does not delete last image.
int operator== (const Image &)
Only compare pointers.
Image & operator= (const Image &)
Operator for copy image.
Image & operator+ (const Image &)
Logical Add for each pixel.
Image & operator+= (const Image &)
Logical Acomulate for each pixel.
Image & operator- (const Image &)
Logical Substraction for each pixel.
Image & operator-= (const Image &)
Logical Substraction for each pixel.
Image & operator* (const Image &)
Matrix multiply.
Image & operator*= (const Image &)
Matrix Multiply.
Image & operator* (double)
Multiply each pixel.
Image & operator*= (double)
Multiply each pixel.
Image & operator/ (double value)
Divide each pixel.
Image & operator/= (double value)
Divide each pixel.
Image & operator! ()
Logical binary Not for each pixel.
Image & operator& (const Image &)
Logical binary And for each pixel.
Image & operator&= (const Image &)
Logical binary And for each pixel.
Image & operator| (const Image &)
Logical binary Or for each pixel.
Image & operator|= (const Image &)
Logical binary Or for each pixel.
Image & operator^ (const Image &)
Logical binary Xor for each pixel.
Image & operator^= (const Image &)
Logical binary Xor for each pixel.
Image & absDiff (const Image &)
Absolute difference for each pixel.
Image * clone () const
Copy's the image in separete region of memory.
void resize (CvSize, int=Nearest)
Utility to convert Image's Color type.
void convert (int)
Utility to convert this Image's Color type.
void flip ()
Flips Image horizontaly.
void showImage (const char *)
Static Public Member Functions
static Image * convert (const Image *, int)
Utility to convert Image's Color type.
static Image * resize (const Image *, CvSize, int=Nearest)
Utility to convert Image's Color type.
Protected Attributes
IplImage * m_image
Detailed Description
Image Implements General Constructors an utilities for manipulate images or CvArray-based Matrix.
Constructor & Destructor Documentation
OpenCV::Bitmap::Image::Image ()
Referenced by absDiff(), clone(), convert(), operator!(), operator&(), operator*(), operator+(), operator-(), operator^(), operator|(), resize(), and OpenCV::Bitmap::ProcessableImage::warpPerspective().
OpenCV::Bitmap::Image::Image (const Image & image)
OpenCV::Bitmap::Image::Image (IplImage * image)
OpenCV::Bitmap::Image::Image (const char * imagePath) throw (FileNotFoundException) [explicit]
OpenCV::Bitmap::Image::Image (CvSize size, int depth = UByte, int channels = 3)
Default Constructor.
Parameters:
[in] size Image's Size
[in] depth Image's color depth. By default UByte
[in] channels Image's channels count. 3 for color[Default] 1 for B/W
References m_image.
OpenCV::Bitmap::Image::~Image () [virtual]
References m_image.
Member Function Documentation
Image & OpenCV::Bitmap::Image::absDiff (const Image & image)
Absolute difference for each pixel.
References depth(), Image(), m_image, numberOfChannels(), and size().
Image * OpenCV::Bitmap::Image::clone () const
Copy's the image in separete region of memory.
References Image(), and m_image.
Referenced by OpenCV::Bitmap::Histogram::equalizeHist(), main(), OpenCV::VectorizedGraphics::OpticalObject::maskFromUnconnectedMask(), OpenCV::Bitmap::ProcessableImage::morphologyEx(), OpenCV::VectorizedGraphics::OpticalObject::opticalObjectsFromImage(), and OpenCV::VectorizedGraphics::OpticalFlowLK::seedImage().
void OpenCV::Bitmap::Image::convert (int flags)
Utility to convert this Image's Color type.
Parameters:
[in] flags Conversion Flags, from enum Conversion
Reimplemented in OpenCV::Bitmap::ProcessableImage.
References m_image, size(), and OpenCV::Bitmap::UByte.
Image * OpenCV::Bitmap::Image::convert (const Image * image, int flags) [static]
Utility to convert Image's Color type.
Parameters:
[in] image Image to be converted
[in] flags Conversion Flags, from enum Conversion
Returns:
Converted Image
References Image(), m_image, size(), and OpenCV::Bitmap::UByte.
Referenced by OpenCV::VectorizedGraphics::OpticalFlowLK::calcOpticalFlow(), OpenCV::MachineLearning::HaarClassifier::findObjects(), OpenCV::Bitmap::CodeBookSubstraction::generateBackground(), OpenCV::VectorizedGraphics::OpticalObject::maskFromUnconnectedMask(), OpenCV::VectorizedGraphics::OpticalObject::opticalObjectsFromImage(), OpenCV::VectorizedGraphics::OpticalFlowLK::seedImage(), and OpenCV::Bitmap::CodeBookSubstraction::toYUV().
IplImage* OpenCV::Bitmap::Image::cvImage () const [inline]
Gets pointer to OpenCV's image format.
References m_image.
Referenced by OpenCV::Bitmap::Histogram::calcBackProjection(), OpenCV::VectorizedGraphics::OpticalFlowLK::calcOpticalFlow(), OpenCV::Bitmap::Histogram::create1ChHistogram(), OpenCV::Bitmap::Histogram::createHSHistogram(), OpenCV::Bitmap::Histogram::createRGBHistogram(), OpenCV::Bitmap::Histogram::equalizeHist(), OpenCV::MachineLearning::HaarClassifier::findObjects(), OpenCV::Bitmap::CodeBookSubstraction::learnBackground(), OpenCV::VectorizedGraphics::OpticalObject::maskFromUnconnectedMask(), OpenCV::VectorizedGraphics::OpticalObject::polygonalContours(), OpenCV::VectorizedGraphics::OpticalFlowLK::seedImage(), OpenCV::Tracking::OFLKTracker::startTracking(), OpenCV::Tracking::MeanShift::startTracking(), OpenCV::Tracking::MeanShift::track(), OpenCV::Tracking::CAMShift::track(), and OpenCV::VideoIO::VideoWriter::writeFrame().
int OpenCV::Bitmap::Image::depth () const [inline]
Gets Color Depth from enum Depth.
References m_image.
Referenced by absDiff(), OpenCV::Bitmap::ProcessableImage::convert(), operator!(), operator&(), operator*(), operator+(), operator-(), operator^(), operator|(), resize(), and GUI::ImageViewWidget::showImage().
void OpenCV::Bitmap::Image::flip () [inline]
Flips Image horizontaly.
References m_image.
int OpenCV::Bitmap::Image::height () const [inline]
References m_image.
Referenced by OpenCV::Bitmap::DrawableImage::clear(), OpenCV::MachineLearning::HaarClassifier::findObjects(), GUI::ImageViewWidget::showImage(), OpenCV::Tracking::MeanShift::track(), and OpenCV::Tracking::CAMShift::track().
int OpenCV::Bitmap::Image::numberOfChannels () const [inline]
Gets channels Count. 3 for color or 1 for BW.
References m_image.
Referenced by absDiff(), OpenCV::VectorizedGraphics::OpticalFlowLK::calcOpticalFlow(), OpenCV::MachineLearning::HaarClassifier::findObjects(), OpenCV::VectorizedGraphics::OpticalObject::maskFromUnconnectedMask(), operator!(), operator&(), operator*(), operator+(), operator-(), operator^(), operator|(), OpenCV::VectorizedGraphics::OpticalObject::opticalObjectsFromImage(), OpenCV::VectorizedGraphics::OpticalObject::polygonalContours(), resize(), OpenCV::VectorizedGraphics::OpticalFlowLK::seedImage(), and GUI::ImageViewWidget::showImage().
Image & OpenCV::Bitmap::Image::operator! ()
Logical binary Not for each pixel.
References depth(), Image(), m_image, numberOfChannels(), and size().
Image & OpenCV::Bitmap::Image::operator& (const Image & image)
Logical binary And for each pixel.
References depth(), Image(), m_image, numberOfChannels(), and size().
Image & OpenCV::Bitmap::Image::operator&= (const Image & image)
Logical binary And for each pixel.
References m_image.
Image& OpenCV::Bitmap::Image::operator* (double)
Multiply each pixel.
Todo:
Image & OpenCV::Bitmap::Image::operator* (const Image & image)
Matrix multiply.
References depth(), Image(), m_image, numberOfChannels(), and size().
Image& OpenCV::Bitmap::Image::operator*= (double)
Multiply each pixel.
Todo:
Image & OpenCV::Bitmap::Image::operator*= (const Image & image)
Matrix Multiply.
References m_image.
Image & OpenCV::Bitmap::Image::operator+ (const Image & image)
Logical Add for each pixel.
References depth(), Image(), m_image, numberOfChannels(), and size().
Image & OpenCV::Bitmap::Image::operator+= (const Image & image)
Logical Acomulate for each pixel.
References m_image.
Image & OpenCV::Bitmap::Image::operator- (const Image & image)
Logical Substraction for each pixel.
References depth(), Image(), m_image, numberOfChannels(), and size().
Image & OpenCV::Bitmap::Image::operator-= (const Image & image)
Logical Substraction for each pixel.
References m_image.
Image& OpenCV::Bitmap::Image::operator/ (double value) [inline]
Divide each pixel.
Image& OpenCV::Bitmap::Image::operator/= (double value) [inline]
Divide each pixel.
Image & OpenCV::Bitmap::Image::operator= (const Image & image)
Operator for copy image.
References m_image.
int OpenCV::Bitmap::Image::operator== (const Image & image)
Only compare pointers.
References m_image.
Image & OpenCV::Bitmap::Image::operator^ (const Image & image)
Logical binary Xor for each pixel.
References depth(), Image(), m_image, numberOfChannels(), and size().
Image & OpenCV::Bitmap::Image::operator^= (const Image & image)
Logical binary Xor for each pixel.
References m_image.
Image & OpenCV::Bitmap::Image::operator| (const Image & image)
Logical binary Or for each pixel.
References depth(), Image(), m_image, numberOfChannels(), and size().
Image & OpenCV::Bitmap::Image::operator|= (const Image & image)
Logical binary Or for each pixel.
References m_image.
char* OpenCV::Bitmap::Image::rawData () [inline]
Gets pointer for image's RAW data(Bitmap). Be careful with big-endian processors.
References m_image.
Referenced by OpenCV::Bitmap::CodeBookSubstraction::codeBookDepth(), OpenCV::Bitmap::CodeBookSubstraction::generateBackground(), GUI::ImageViewWidget::showImage(), and OpenCV::Bitmap::CodeBookSubstraction::subtractBackground().
void OpenCV::Bitmap::Image::resize (CvSize newSize, int method = Nearest)
Utility to convert Image's Color type.
Parameters:
[in] newSize Returned image's new size
[in] method Resize Method. From enum InterpolationMethod
References depth(), m_image, and numberOfChannels().
Image * OpenCV::Bitmap::Image::resize (const Image * image, CvSize newSize, int method = Nearest) [static]
Utility to convert Image's Color type.
Parameters:
[in] image Image to be converted
[in] newSize Returned image's new size
[in] method Resize Method. From enum InterpolationMethod
Returns:
Resized Image
References depth(), Image(), m_image, and numberOfChannels().
Referenced by OpenCV::MachineLearning::HaarClassifier::findObjects(), OpenCV::Bitmap::CodeBookSubstraction::learnBackground(), and OpenCV::Bitmap::CodeBookSubstraction::subtractBackground().
void OpenCV::Bitmap::Image::setCvImage (IplImage * cvImage) [inline]
Sets OpenCV's Image. It does not delete last image.
References m_image.
void OpenCV::Bitmap::Image::showImage (const char * windowName)
References m_image.
Referenced by main(), and HumanInterface::ScreenRecognizer::newFrameForRecognize().
CvSize OpenCV::Bitmap::Image::size () const [inline]
Gets Image's Size.
References m_image.
Referenced by absDiff(), OpenCV::Bitmap::Histogram::calcBackProjection(), OpenCV::Bitmap::DrawableImage::clear(), OpenCV::Bitmap::ProcessableImage::convert(), convert(), OpenCV::Bitmap::Histogram::createHSHistogram(), OpenCV::Bitmap::Histogram::createRGBHistogram(), main(), OpenCV::VectorizedGraphics::OpticalObject::maskFromUnconnectedMask(), HumanInterface::ScreenRecognizer::newFrameForRecognize(), operator!(), operator&(), operator*(), operator+(), operator-(), operator^(), operator|(), OpenCV::Tracking::OFLKTracker::startTracking(), OpenCV::Tracking::MeanShift::startTracking(), OpenCV::Bitmap::CodeBookSubstraction::subtractBackground(), OpenCV::Tracking::OFLKTracker::track(), and OpenCV::Bitmap::ProcessableImage::warpPerspective().
int OpenCV::Bitmap::Image::width () const [inline]
References m_image.
Referenced by OpenCV::Bitmap::DrawableImage::clear(), OpenCV::MachineLearning::HaarClassifier::findObjects(), GUI::ImageViewWidget::showImage(), OpenCV::Tracking::MeanShift::track(), and OpenCV::Tracking::CAMShift::track().
Member Data Documentation
IplImage* OpenCV::Bitmap::Image::m_image [protected]
Referenced by absDiff(), OpenCV::Bitmap::ProcessableImage::adaptiveThreshold(), OpenCV::Bitmap::ProcessableImage::canny(), clone(), OpenCV::Bitmap::ProcessableImage::convert(), convert(), cvImage(), depth(), OpenCV::Bitmap::DrawableImage::drawBox(), OpenCV::Bitmap::DrawableImage::drawCircle(), OpenCV::Bitmap::DrawableImage::drawContour(), OpenCV::Bitmap::DrawableImage::drawLine(), OpenCV::Bitmap::DrawableImage::drawObject(), OpenCV::Bitmap::DrawableImage::drawRectangle(), OpenCV::Bitmap::DrawableImage::drawText(), OpenCV::Bitmap::ProcessableImage::findChessboardCorners(), flip(), height(), Image(), OpenCV::Bitmap::ProcessableImage::inpaint(), OpenCV::Bitmap::ProcessableImage::meanShiftFiltering(), OpenCV::Bitmap::ProcessableImage::morphologyEx(), numberOfChannels(), operator!(), operator&(), operator&=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator=(), operator==(), operator^(), operator^=(), operator|(), operator|=(), rawData(), resize(), setCvImage(), showImage(), size(), OpenCV::Bitmap::ProcessableImage::sobel(), OpenCV::Bitmap::ProcessableImage::threshold(), OpenCV::Bitmap::ProcessableImage::warpPerspective(), width(), OpenCV::Bitmap::DrawableImage::~DrawableImage(), ~Image(), and OpenCV::Bitmap::ProcessableImage::~ProcessableImage().
The documentation for this class was generated from the following files:
Image.h
Image.cpp