CVTrackpad: HumanInterface::Hand Class Reference
HumanInterface::Hand Class Reference
Hand Provides Methods for find hand in one Image from several input forms.
#include <Hand.h>
Public Member Functions
virtual ~Hand ()
OpticalObject * opticalObject ()
Getter for OpticalObject of hand. Protected inheritance.
Histogram * skinColor () const
Getter for skin Color.
template<class t_tracker >
t_tracker * handTracker (const Image *image=NULL)
Generates tracker for hand.
Static Public Member Functions
static Hand * handFromFaceCascade (const HaarClassifier *, const Image *, const Mask *=NULL, CvRect *=NULL)
Default Constructor.
static Hand * handFromHistogram (const Histogram *, const Image *, const Mask *=NULL)
Default Constructor.
Protected Member Functions
Hand ()
Hand (const Hand &)
Hand (const OpticalObject &)
Hand (const OpticalObject *, const Image *)
Hand (const OpticalObject *, const Histogram *)
Protected Attributes
Histogram * m_skinColor
Static Private Member Functions
static bool findFace (const HaarClassifier *, const Image *, CvRect *, Histogram **)
static OpticalObject * findHandObject (const Image *, const Histogram *, const Mask *=NULL, CvRect *=NULL, double=CORRELATION_THRESHOLD)
Detailed Description
Hand Provides Methods for find hand in one Image from several input forms.
Todo:
Support for more tha one hand
Constructor & Destructor Documentation
HumanInterface::Hand::~Hand () [virtual]
References m_skinColor.
HumanInterface::Hand::Hand () [protected]
Referenced by handFromFaceCascade().
HumanInterface::Hand::Hand (const Hand & hand) [protected]
HumanInterface::Hand::Hand (const OpticalObject & optObj) [protected]
HumanInterface::Hand::Hand (const OpticalObject * handObject, const Image * image) [protected]
References OpenCV::Bitmap::COLOR_WHITE, OpenCV::Bitmap::Histogram::createHSHistogram(), OpenCV::Bitmap::DrawableImage::drawObject(), m_skinColor, and OpenCV::Bitmap::UByte.
HumanInterface::Hand::Hand (const OpticalObject * , const Histogram *) [protected]
Member Function Documentation
static bool HumanInterface::Hand::findFace (const HaarClassifier * , const Image * , CvRect * , Histogram **) [static, private]
Referenced by handFromFaceCascade().
static OpticalObject* HumanInterface::Hand::findHandObject (const Image * , const Histogram * , const Mask * = NULL, CvRect * = NULL, double = CORRELATION_THRESHOLD) [static, private]
Referenced by handFromFaceCascade().
Hand * HumanInterface::Hand::handFromFaceCascade (const HaarClassifier * faceCascade, const Image * image, const Mask * probabilisticMap = NULL, CvRect * faceRect = NULL) [static]
Default Constructor.
Parameters:
[in] faceCascade HaarClassifier for face.
[in] image Image in witch find hand.
[in] probabilisticMap Mask of extern probabilistic map. By default NULL
[out] faceRect Rect to store face.
References findFace(), findHandObject(), and Hand().
static Hand* HumanInterface::Hand::handFromHistogram (const Histogram * , const Image * , const Mask * = NULL) [static]
Default Constructor.
Parameters:
[in] histogram Histogram for Skin color.
[in] image Image in witch find hand.
[in] probabilisticMap Mask of extern probabilistic map. By default NULL
template<class t_tracker > t_tracker* HumanInterface::Hand::handTracker (const Image * image = NULL) [inline]
Generates tracker for hand.
References OpenCV::VectorizedGraphics::OpticalObject::connectedComponents().
Referenced by main().
OpticalObject* HumanInterface::Hand::opticalObject () [inline]
Getter for OpticalObject of hand. Protected inheritance.
Referenced by main().
Histogram* HumanInterface::Hand::skinColor () const [inline]
Getter for skin Color.
References m_skinColor.
Member Data Documentation
Histogram* HumanInterface::Hand::m_skinColor [protected]
Referenced by Hand(), skinColor(), and ~Hand().
The documentation for this class was generated from the following files:
Hand.h
Hand.cpp