CVTrackpad: OpenCV::Tracking::OFLKTracker Class Reference
OpenCV::Tracking::OFLKTracker Class Reference
OFLKTracker Implements tracking algorithm based on Lucas-Kanade optical flow that not depends of object's color.
#include <OFLKTracker.h>
Public Member Functions
OFLKTracker ()
OFLKTracker (const OFLKTracker &)
OFLKTracker (const Image *, const CvConnectedComp *)
Constructor and start tracking.
OFLKTracker (const Image *, CvRect, const Mask *=NULL)
Constructor and start tracking.
virtual ~OFLKTracker ()
virtual void startTracking (const Image *, const CvConnectedComp *)
Constructor and start tracking.
virtual void startTracking (const Image *, CvRect, const Mask *=NULL)
Constructor and start tracking.
virtual CvConnectedComp * track (const Image *, const Mask *=NULL)
Tracks object on image.
Protected Attributes
OpticalFlowLK * m_oflk
CvRect m_lastPosition
Static Private Member Functions
static Vector2D32f standardVector (Flow *)
Detailed Description
OFLKTracker Implements tracking algorithm based on Lucas-Kanade optical flow that not depends of object's color.
Constructor & Destructor Documentation
OpenCV::Tracking::OFLKTracker::OFLKTracker () [inline]
OpenCV::Tracking::OFLKTracker::OFLKTracker (const OFLKTracker & oflkTracker)
OpenCV::Tracking::OFLKTracker::OFLKTracker (const Image * image, const CvConnectedComp * cc)
Constructor and start tracking.
Parameters:
[in] image Image to start tracking
[in] cc Object to be tracked
References startTracking().
OpenCV::Tracking::OFLKTracker::OFLKTracker (const Image * image, CvRect rect, const Mask * mask = NULL)
Constructor and start tracking.
Parameters:
[in] image Image to start tracking
[in] rect Object's rect
[in] mask Object's mask
References startTracking().
OpenCV::Tracking::OFLKTracker::~OFLKTracker () [virtual]
References m_oflk.
Member Function Documentation
Vector2D32f OpenCV::Tracking::OFLKTracker::standardVector (Flow * flow) [static, private]
References OpenCV::Tracking::BACKGROUNG_VECTOR_LENGHT, OpenCV::VectorizedGraphics::Vector2D32f::dx(), and OpenCV::VectorizedGraphics::Vector2D32f::dy().
Referenced by track().
void OpenCV::Tracking::OFLKTracker::startTracking (const Image * image, CvRect rect, const Mask * mask = NULL) [virtual]
Constructor and start tracking.
Parameters:
[in] image Image to start tracking
[in] rect Object's rect
[in] mask Object's mask
References OpenCV::Bitmap::DrawableImage::drawBox(), m_lastPosition, m_oflk, OpenCV::Tracking::MAX_POINTS_TO_TRACK, OpenCV::Bitmap::Image::size(), and OpenCV::Bitmap::UByte.
void OpenCV::Tracking::OFLKTracker::startTracking (const Image * image, const CvConnectedComp * cComp) [virtual]
Constructor and start tracking.
Parameters:
[in] image Image to start tracking
[in] cComp Object to be tracked
Reimplemented from OpenCV::Tracking::Tracker.
References OpenCV::Bitmap::Image::cvImage(), OpenCV::Bitmap::Image::size(), and OpenCV::Bitmap::UByte.
Referenced by OFLKTracker().
CvConnectedComp * OpenCV::Tracking::OFLKTracker::track (const Image * image, const Mask * = NULL) [virtual]
Tracks object on image.
Parameters:
[in] image Image to be tracked
Returns:
ConnectedComponent of new object.
Reimplemented from OpenCV::Tracking::Tracker.
References OpenCV::VectorizedGraphics::OpticalFlowLK::calcOpticalFlow(), OpenCV::Bitmap::DrawableImage::drawBox(), OpenCV::VectorizedGraphics::Vector2D32f::dx(), OpenCV::VectorizedGraphics::Vector2D32f::dy(), m_lastPosition, m_oflk, OpenCV::VectorizedGraphics::OpticalFlowLK::seedImage(), OpenCV::Bitmap::Image::size(), standardVector(), and OpenCV::Bitmap::UByte.
Member Data Documentation
CvRect OpenCV::Tracking::OFLKTracker::m_lastPosition [protected]
Referenced by startTracking(), and track().
OpticalFlowLK* OpenCV::Tracking::OFLKTracker::m_oflk [protected]
Referenced by startTracking(), track(), and ~OFLKTracker().
The documentation for this class was generated from the following files:
OFLKTracker.h
OFLKTracker.cpp