CVTrackpad: OpenCV::Bitmap::CodeBookSubstraction Class Reference
OpenCV::Bitmap::CodeBookSubstraction Class Reference
CodeBookSubstraction Inherits from BackgroundSubtraction.
#include <BackgroundSubtraction.h>
Public Member Functions
CodeBookSubstraction ()
CodeBookSubstraction (const CodeBookSubstraction &)
CodeBookSubstraction (const Image *, int=CHANNELS_COUNT)
Default Constructor.
virtual ~CodeBookSubstraction ()
CvScalar bounds () const
void setBounds (const CvScalar &bounds)
virtual void learnBackground (const Image *)
Method for learning Background.
virtual Mask * subtractBackground (const Image *)
Method for Substracting Background.
Mask * codeBookDepth ()
Image * generateBackground ()
Protected Member Functions
unsigned char diffPixel (unsigned char *, CodeBook &)
CodeBookEntry * updateCodebook (unsigned char *, CodeBook &)
long clearObsoleteEntries (CodeBook &)
Protected Attributes
std::vector< CodeBook > m_codeBooksVector
CvScalar m_bounds
int m_channelsCount
Private Member Functions
Image * toYUV (const Image *image)
Private Attributes
unsigned long m_lastClearTime
Detailed Description
CodeBookSubstraction Inherits from BackgroundSubtraction.
Implements CodeBook algorithm for background substraction. Generates one dictionary of last values of each pixel. This algorithm learns also not static background.
Constructor & Destructor Documentation
OpenCV::Bitmap::CodeBookSubstraction::CodeBookSubstraction ()
OpenCV::Bitmap::CodeBookSubstraction::CodeBookSubstraction (const CodeBookSubstraction & cbs)
References OpenCV::Bitmap::CODEBOOK_RESOLUTION, and m_codeBooksVector.
OpenCV::Bitmap::CodeBookSubstraction::CodeBookSubstraction (const Image * image, int channelsCount = CHANNELS_COUNT)
Default Constructor.
Parameters:
[in] image Image of background
[in] channelsCount Channels count. 1 faster, 3 better[default]
References learnBackground().
OpenCV::Bitmap::CodeBookSubstraction::~CodeBookSubstraction () [virtual]
References m_codeBooksVector.
Member Function Documentation
CvScalar OpenCV::Bitmap::CodeBookSubstraction::bounds () const [inline]
References m_bounds.
long OpenCV::Bitmap::CodeBookSubstraction::clearObsoleteEntries (CodeBook & cb) [protected]
References OpenCV::Bitmap::TIME_TO_ASUME_OBSOLETE.
Referenced by learnBackground(), and subtractBackground().
Mask * OpenCV::Bitmap::CodeBookSubstraction::codeBookDepth ()
References OpenCV::Bitmap::CODEBOOK_RESOLUTION, m_codeBooksVector, OpenCV::Bitmap::Image::rawData(), and OpenCV::Bitmap::UByte.
unsigned char OpenCV::Bitmap::CodeBookSubstraction::diffPixel (unsigned char * pixel, CodeBook & cb) [protected]
References OpenCV::Bitmap::CodeBookEntry::lastUpdate, m_channelsCount, and OpenCV::Bitmap::CodeBookEntry::timeOnScene.
Referenced by subtractBackground().
Image * OpenCV::Bitmap::CodeBookSubstraction::generateBackground ()
References OpenCV::Bitmap::CODEBOOK_RESOLUTION, OpenCV::Bitmap::Image::convert(), OpenCV::Bitmap::CodeBookEntry::learnHigh, OpenCV::Bitmap::CodeBookEntry::learnLow, m_codeBooksVector, OpenCV::Bitmap::Image::rawData(), OpenCV::Bitmap::CodeBookEntry::timeOnScene, OpenCV::Bitmap::UByte, and OpenCV::Bitmap::YUVToColor.
void OpenCV::Bitmap::CodeBookSubstraction::learnBackground (const Image * image) [virtual]
Method for learning Background.
Must be called as many times as could be for better performance.
Parameters:
[in] image Image of background
References clearObsoleteEntries(), OpenCV::Bitmap::CODEBOOK_RESOLUTION, OpenCV::Bitmap::Image::cvImage(), m_codeBooksVector, m_lastClearTime, OpenCV::Bitmap::Image::resize(), OpenCV::Bitmap::TIME_TO_ASUME_OBSOLETE, toYUV(), and updateCodebook().
Referenced by CodeBookSubstraction(), and main().
void OpenCV::Bitmap::CodeBookSubstraction::setBounds (const CvScalar & bounds) [inline]
References m_bounds.
Mask * OpenCV::Bitmap::CodeBookSubstraction::subtractBackground (const Image * image) [virtual]
Method for Substracting Background.
Also learns Background. Call after learnBackground
Parameters:
[in] image Image to be substract
Returns:
Background substraction Mask.
References OpenCV::Bitmap::Bilineal, OpenCV::Bitmap::CLEAR_RATE, clearObsoleteEntries(), OpenCV::Bitmap::CODEBOOK_RESOLUTION, diffPixel(), m_codeBooksVector, m_lastClearTime, OpenCV::Bitmap::Image::rawData(), OpenCV::Bitmap::Image::resize(), OpenCV::Bitmap::Image::size(), OpenCV::Bitmap::TIME_TO_ASUME_OBSOLETE, toYUV(), OpenCV::Bitmap::UByte, and updateCodebook().
Referenced by main().
Image* OpenCV::Bitmap::CodeBookSubstraction::toYUV (const Image * image) [inline, private]
References OpenCV::Bitmap::Image::convert().
Referenced by learnBackground(), and subtractBackground().
CodeBookEntry * OpenCV::Bitmap::CodeBookSubstraction::updateCodebook (unsigned char * pixel, CodeBook & cb) [protected]
References OpenCV::Bitmap::CodeBookEntry::lastUpdate, OpenCV::Bitmap::CodeBookEntry::learnHigh, OpenCV::Bitmap::CodeBookEntry::learnLow, m_bounds, m_channelsCount, OpenCV::Bitmap::CodeBookEntry::max, OpenCV::Bitmap::CodeBookEntry::min, and OpenCV::Bitmap::CodeBookEntry::timeOnScene.
Referenced by learnBackground(), and subtractBackground().
Member Data Documentation
CvScalar OpenCV::Bitmap::CodeBookSubstraction::m_bounds [protected]
Referenced by bounds(), setBounds(), and updateCodebook().
int OpenCV::Bitmap::CodeBookSubstraction::m_channelsCount [protected]
Referenced by diffPixel(), and updateCodebook().
std::vector<CodeBook> OpenCV::Bitmap::CodeBookSubstraction::m_codeBooksVector [protected]
Referenced by codeBookDepth(), CodeBookSubstraction(), generateBackground(), learnBackground(), subtractBackground(), and ~CodeBookSubstraction().
unsigned long OpenCV::Bitmap::CodeBookSubstraction::m_lastClearTime [private]
Referenced by learnBackground(), and subtractBackground().
The documentation for this class was generated from the following files:
BackgroundSubtraction.h
BackgroundSubtraction.cpp