CVTrackpad: OpenCV::Bitmap Namespace Reference
OpenCV::Bitmap Namespace Reference
Classes
class BackgroundSubtraction
BackgroundSubtraction Abstract class for Background substraction algorithms.
struct CodeBookEntry
CodeBookEntry CodeBook's entry.
class CodeBookSubstraction
CodeBookSubstraction Inherits from BackgroundSubtraction.
class DrawableImage
DrawableImage Implements Image's Methods for it's modification by drawing.
class Histogram
Histogram Support for probabilistics histograms and methods for it's manipulation.
class Image
Image Implements General Constructors an utilities for manipulate images or CvArray-based Matrix.
class ProcessableImage
ProcessableImage Implements methods fore Image processing.
Typedefs
typedef std::vector
< CodeBookEntry * > CodeBook
typedef CvArr Signature
typedef Image Mask
Mask is a one channel Image.
Enumerations
enum ComparisonMethod { Correlation = CV_COMP_CORREL, ChiSquare = CV_COMP_CHISQR, Intersection = CV_COMP_INTERSECT, BhattacharyyaDistance = CV_COMP_BHATTACHARYYA }
Method for Comparison between histograms.
enum HistogramType { Array = CV_HIST_ARRAY, Sparse = CV_HIST_SPARSE }
Histogram type: Array or Sparse histogram.
enum DistanceType { ManhattanDistance = CV_DIST_L1, EuclideanDistance = CV_DIST_L2 }
Distance type for EMD2 (Earth Mover's Distance).
enum InterpolationMethod { Nearest = CV_INTER_NN, Bilineal = CV_INTER_LINEAR, AreaResampling = CV_INTER_AREA, Bicubic = CV_INTER_CUBIC }
Diferent Methods to interpolate an image.
enum Depth {
UByte = IPL_DEPTH_8U, SByte = IPL_DEPTH_8S, UShort = IPL_DEPTH_16U, SShort = IPL_DEPTH_16S,
SLong = IPL_DEPTH_32S, Float32 = IPL_DEPTH_32F, Float64 = IPL_DEPTH_64F
}
Image's channel's depth.
enum Conversion {
ColorToGray = CV_BGR2GRAY, GrayToColor = CV_GRAY2BGR, ColorToHSV = CV_BGR2HSV, HSVToColor = CV_HSV2BGR,
ColorToYUV = CV_BGR2YCrCb, YUVToColor = CV_BGR2YCrCb
}
Color type Conversion.
enum ThresholdType {
Binary = CV_THRESH_BINARY, BinaryInv = CV_THRESH_BINARY_INV, MaskThres = CV_THRESH_MASK, Otsu = CV_THRESH_OTSU,
ToZero = CV_THRESH_TOZERO, ToZeroInv = CV_THRESH_TOZERO_INV, Trunc = CV_THRESH_TRUNC
}
Threshold result type.
enum MorphologyOperator {
Blackhat = CV_MOP_BLACKHAT, Open = CV_MOP_OPEN, Gradient = CV_MOP_GRADIENT, Close = CV_MOP_CLOSE,
Tophat = CV_MOP_TOPHAT
}
Mopholgy operators.
enum InpaintMethod { NavierStokes = CV_INPAINT_NS, Telea = CV_INPAINT_TELEA }
Inpaint algorithms. Refer to OpenCV's documantation.
enum AdaptiveThresholdType { Mean = CV_ADAPTIVE_THRESH_MEAN_C, Gaussian = CV_ADAPTIVE_THRESH_GAUSSIAN_C }
Adaptive Thredhold type.
Variables
const CvScalar DEFAULT_BOUND = cvScalar(14, 10, 10)
const CvSize CODEBOOK_RESOLUTION = cvSize(100, 75)
const unsigned long TIME_TO_ASUME_OBSOLETE = 5 * CLOCKS_PER_SEC
const int CLEAR_RATE = 4
const CvScalar COLOR_WHITE = cvScalar(255, 255, 255)
const CvScalar COLOR_GRAY = cvScalar(127, 127, 127)
const CvScalar COLOR_BLACK = cvScalar(0, 0, 0)
const CvScalar COLOR_BLUE = cvScalar(255, 0, 0)
const CvScalar COLOR_GREEN = cvScalar(0, 255, 0)
const CvScalar COLOR_RED = cvScalar(0, 0, 255)
Typedef Documentation
typedef std::vector<CodeBookEntry*> OpenCV::Bitmap::CodeBook
typedef Image OpenCV::Bitmap::Mask
Mask is a one channel Image.
typedef CvArr OpenCV::Bitmap::Signature
Enumeration Type Documentation
enum OpenCV::Bitmap::AdaptiveThresholdType
Adaptive Thredhold type.
Enumerator:
Mean
Gaussian
enum OpenCV::Bitmap::ComparisonMethod
Method for Comparison between histograms.
Enumerator:
Correlation
ChiSquare
Intersection
BhattacharyyaDistance
enum OpenCV::Bitmap::Conversion
Color type Conversion.
Enumerator:
ColorToGray
GrayToColor
ColorToHSV
HSVToColor
ColorToYUV
YUVToColor
enum OpenCV::Bitmap::Depth
Image's channel's depth.
Enumerator:
UByte
SByte
UShort
SShort
SLong
Float32
Float64
enum OpenCV::Bitmap::DistanceType
Distance type for EMD2 (Earth Mover's Distance).
Enumerator:
ManhattanDistance
EuclideanDistance
enum OpenCV::Bitmap::HistogramType
Histogram type: Array or Sparse histogram.
Enumerator:
Array
Sparse
enum OpenCV::Bitmap::InpaintMethod
Inpaint algorithms. Refer to OpenCV's documantation.
Enumerator:
NavierStokes
Telea
enum OpenCV::Bitmap::InterpolationMethod
Diferent Methods to interpolate an image.
Enumerator:
Nearest
Bilineal
AreaResampling
Bicubic
enum OpenCV::Bitmap::MorphologyOperator
Mopholgy operators.
Enumerator:
Blackhat
Open
Gradient
Close
Tophat
enum OpenCV::Bitmap::ThresholdType
Threshold result type.
Enumerator:
Binary
BinaryInv
MaskThres
Otsu
ToZero
ToZeroInv
Trunc
Variable Documentation
const int OpenCV::Bitmap::CLEAR_RATE = 4
Referenced by OpenCV::Bitmap::CodeBookSubstraction::subtractBackground().
const CvSize OpenCV::Bitmap::CODEBOOK_RESOLUTION = cvSize(100, 75)
Referenced by OpenCV::Bitmap::CodeBookSubstraction::codeBookDepth(), OpenCV::Bitmap::CodeBookSubstraction::CodeBookSubstraction(), OpenCV::Bitmap::CodeBookSubstraction::generateBackground(), OpenCV::Bitmap::CodeBookSubstraction::learnBackground(), and OpenCV::Bitmap::CodeBookSubstraction::subtractBackground().
const CvScalar OpenCV::Bitmap::COLOR_BLACK = cvScalar(0, 0, 0)
const CvScalar OpenCV::Bitmap::COLOR_BLUE = cvScalar(255, 0, 0)
const CvScalar OpenCV::Bitmap::COLOR_GRAY = cvScalar(127, 127, 127)
const CvScalar OpenCV::Bitmap::COLOR_GREEN = cvScalar(0, 255, 0)
Referenced by main().
const CvScalar OpenCV::Bitmap::COLOR_RED = cvScalar(0, 0, 255)
Referenced by main().
const CvScalar OpenCV::Bitmap::COLOR_WHITE = cvScalar(255, 255, 255)
Referenced by HumanInterface::Hand::Hand(), and main().
const CvScalar OpenCV::Bitmap::DEFAULT_BOUND = cvScalar(14, 10, 10)
const unsigned long OpenCV::Bitmap::TIME_TO_ASUME_OBSOLETE = 5 * CLOCKS_PER_SEC
Referenced by OpenCV::Bitmap::CodeBookSubstraction::clearObsoleteEntries(), OpenCV::Bitmap::CodeBookSubstraction::learnBackground(), and OpenCV::Bitmap::CodeBookSubstraction::subtractBackground().